name: Security

on:
  push:
    branches: [main]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Dependency scan
        run: |
          python -m pip install --upgrade pip pip-audit
          pip-audit --requirement requirements.txt
        continue-on-error: true
